# Generated by Django 5.1.2 on 2024-11-10 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CartridgeResistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LiquidStrength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LiquidVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PodModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PuffsAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Назва | Смак | Колір"
                    ),
                ),
                ("buy_price", models.PositiveIntegerField(verbose_name="Ціна закупки")),
                (
                    "sell_price",
                    models.PositiveIntegerField(verbose_name="Ціна продажу"),
                ),
                (
                    "drop_sell_price",
                    models.PositiveIntegerField(verbose_name="Ціна продажу - дроп"),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Залишок")),
                (
                    "sold_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="К-сть проданих одиниць"
                    ),
                ),
                (
                    "drop_sold_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="К-сть проданих одиниць - дроп"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        max_length=13, unique=True, verbose_name="Штрих-код"
                    ),
                ),
                (
                    "pod_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.podmodel",
                        verbose_name="Модель поду",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.producer",
                        verbose_name="Виробник",
                    ),
                ),
                (
                    "resistance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.cartridgeresistance",
                        verbose_name="Опір картриджа",
                    ),
                ),
                (
                    "strength",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.liquidstrength",
                        verbose_name="Міцність рідини",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.liquidvolume",
                        verbose_name="Об'єм рідини",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.producttype",
                        verbose_name="Тип продукту",
                    ),
                ),
                (
                    "puffs_amount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.puffsamount",
                        verbose_name="Кількість тяг",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Ціна продажу")),
                ("amount", models.PositiveIntegerField(verbose_name="К-сть")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="producer",
            name="producer_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.producttype"
            ),
        ),
    ]
