# Generated by Django 5.1.2 on 2024-12-01 18:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuffsAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('buy_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sell_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('drop_sell_price', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('barcode', models.CharField(max_length=13, unique=True)),
                ('pod_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.podmodel')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.producer')),
                ('resistance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.cartridgeresistance')),
                ('strength', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.liquidstrength')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.liquidvolume')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.producttype')),
                ('puffs_amount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.puffsamount')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='producer',
            name='producer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.producttype'),
        ),
    ]
