# Generated by Django 5.1.2 on 2024-11-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_amount_liquidstrength_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartridgeresistance",
            old_name="amount",
            new_name="name",
        ),
    ]
