# Generated by Django 5.1.2 on 2024-12-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductField',
        ),
    ]
