# Generated by Django 5.1.2 on 2024-11-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_amount_cartridgeresistance_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartridgeresistance",
            old_name="name",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="liquidstrength",
            old_name="name",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="liquidvolume",
            old_name="name",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="puffsamount",
            old_name="name",
            new_name="amount",
        ),
    ]
