# Generated by Django 5.1.2 on 2025-01-26 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_productfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='drop_sell_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
