# Generated by Django 5.1.2 on 2024-11-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_name_cartridgeresistance_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartridgeresistance",
            name="amount",
            field=models.FloatField(unique=True),
        ),
        migrations.AlterField(
            model_name="liquidstrength",
            name="amount",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="liquidvolume",
            name="amount",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="podmodel",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="puffsamount",
            name="amount",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
