# Generated by Django 5.1.2 on 2024-10-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
