# Generated by Django 5.1.2 on 2024-10-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_product_buy_price_alter_product_sell_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producer",
            name="producer_type",
        ),
        migrations.AddField(
            model_name="product",
            name="puffs_amount",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Кількість тяг"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="resistance",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Опір картриджа"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="strength",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Міцність рідини"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="volume",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Об'єм рідини"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Залишок"),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                max_length=13, unique=True, verbose_name="Штрих-код"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="buy_price",
            field=models.PositiveIntegerField(verbose_name="Ціна закупки"),
        ),
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="base.location",
                verbose_name="Місце продажу",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Назва | смак"),
        ),
        migrations.AlterField(
            model_name="product",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="base.producer",
                verbose_name="Виробник",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="base.type",
                verbose_name="Тип продукту",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sell_price",
            field=models.PositiveIntegerField(verbose_name="Ціна продажу"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sold_amount",
            field=models.PositiveIntegerField(
                default=0, verbose_name="К-сть проданих одиниць"
            ),
        ),
    ]
