# Generated by Django 5.1.2 on 2024-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_product_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(max_length=20),
        ),
    ]
