# Generated by Django 5.1.2 on 2024-10-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_producer_producer_type_product_puffs_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="drop_sell_price",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ціна продажу - дроп"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="drop_sold_amount",
            field=models.PositiveIntegerField(
                default=0, verbose_name="К-сть проданих одиниць - дроп"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_drop",
            field=models.BooleanField(default=False, verbose_name="Дроп?"),
        ),
    ]
