# Generated by Django 5.1.2 on 2024-10-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_optproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="location",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
