# Generated by Django 5.1.2 on 2024-10-30 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_remove_product_location_delete_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="producer",
            name="producer_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="base.type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Залишок"
            ),
        ),
    ]
